# Generated by Django 5.2.1 on 2025-05-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaccia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paziente',
            name='tipo_diabete',
            field=models.CharField(blank=True, choices=[('T1', 'Tipo 1'), ('T2', 'Tipo 2'), ('G', 'Gestazionale'), ('A', 'Altro')], max_length=2, null=True),
        ),
    ]
